# Generated by Django 4.2.30 on 2026-09-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('venue_code', models.CharField(blank=True, max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField()),
                ('errors', models.JSONField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund')], db_index=True, max_length=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('staff_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('venue_type', models.CharField(choices=[('pub', 'Pub'), ('restaurant', 'Restaurant'), ('function', 'Function Space')], default='pub', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ops.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ops.venue'),
        ),
        migrations.CreateModel(
            name='HourlyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField(db_index=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(db_index=True)),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('void_count', models.PositiveIntegerField(default=0)),
                ('refund_count', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rollups', to='ops.venue')),
            ],
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=64)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_acks', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_acks', to='ops.venue')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['venue', 'timestamp'], name='ops_transac_venue_i_1b7fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp', 'type'], name='ops_transac_timesta_3c3e89_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('venue', 'transaction_id'), name='uniq_venue_transaction_id'),
        ),
        migrations.AddIndex(
            model_name='hourlyrollup',
            index=models.Index(fields=['venue', 'hour_of_day'], name='ops_hourlyr_venue_i_9ec564_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyrollup',
            index=models.Index(fields=['hour_start'], name='ops_hourlyr_hour_st_aec088_idx'),
        ),
        migrations.AddConstraint(
            model_name='hourlyrollup',
            constraint=models.UniqueConstraint(fields=('venue', 'hour_start'), name='uniq_venue_hour_rollup'),
        ),
        migrations.AddIndex(
            model_name='alertacknowledgement',
            index=models.Index(fields=['venue', 'alert_type', 'expires_at'], name='ops_alertac_venue_i_1f05d0_idx'),
        ),
    ]
